# Generated by Django 5.2.5 on 2025-10-02 03:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('idcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('imagen', models.CharField(max_length=255)),
                ('categoria_idcategoria', models.ForeignKey(db_column='categoria_idcategoria', on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.categoria')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSolicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('producto_idproducto', models.ForeignKey(db_column='producto_idproducto', on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.producto')),
                ('servicio_idservicio', models.ForeignKey(db_column='servicio_idservicio', on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.servicio')),
                ('usuario_idusuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'db_table': 'servicio',
            },
        ),
    ]
